import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    // Public custom elements — one subpath per entry, matching the
    // kebab-case filename / tag name (gh-<name>).
    'accordion-item': 'src/components/accordion-item.ts',
    accordion: 'src/components/accordion.ts',
    'alert-dialog': 'src/components/alert-dialog.ts',
    alert: 'src/components/alert.ts',
    'aspect-ratio': 'src/components/aspect-ratio.ts',
    attachment: 'src/components/attachment.ts',
    avatar: 'src/components/avatar.ts',
    badge: 'src/components/badge.ts',
    bubble: 'src/components/bubble.ts',
    breadcrumb: 'src/components/breadcrumb.ts',
    'button-group': 'src/components/button-group.ts',
    button: 'src/components/button.ts',
    calendar: 'src/components/calendar.ts',
    card: 'src/components/card.ts',
    'carousel-item': 'src/components/carousel-item.ts',
    carousel: 'src/components/carousel.ts',
    chart: 'src/components/chart.ts',
    'checkbox-group': 'src/components/checkbox-group.ts',
    checkbox: 'src/components/checkbox.ts',
    collapsible: 'src/components/collapsible.ts',
    combobox: 'src/components/combobox.ts',
    command: 'src/components/command.ts',
    'context-menu': 'src/components/context-menu.ts',
    'date-picker': 'src/components/date-picker.ts',
    direction: 'src/components/direction.ts',
    drawer: 'src/components/drawer.ts',
    empty: 'src/components/empty.ts',
    'form-field': 'src/components/form-field.ts',
    'hover-card': 'src/components/hover-card.ts',
    icon: 'src/components/icon.ts',
    'input-group': 'src/components/input-group.ts',
    'input-otp': 'src/components/input-otp.ts',
    input: 'src/components/input.ts',
    item: 'src/components/item.ts',
    kbd: 'src/components/kbd.ts',
    label: 'src/components/label.ts',
    marker: 'src/components/marker.ts',
    menu: 'src/components/menu.ts',
    menubar: 'src/components/menubar.ts',
    'message-scroller': 'src/components/message-scroller.ts',
    message: 'src/components/message.ts',
    modal: 'src/components/modal.ts',
    'native-select': 'src/components/native-select.ts',
    'navigation-menu': 'src/components/navigation-menu.ts',
    'pagination-item': 'src/components/pagination-item.ts',
    pagination: 'src/components/pagination.ts',
    popover: 'src/components/popover.ts',
    progress: 'src/components/progress.ts',
    'radio-group': 'src/components/radio-group.ts',
    radio: 'src/components/radio.ts',
    'resizable-group': 'src/components/resizable-group.ts',
    'resizable-handle': 'src/components/resizable-handle.ts',
    'resizable-panel': 'src/components/resizable-panel.ts',
    'scroll-area': 'src/components/scroll-area.ts',
    'select-listbox': 'src/components/select-listbox.ts',
    select: 'src/components/select.ts',
    separator: 'src/components/separator.ts',
    sheet: 'src/components/sheet.ts',
    sidebar: 'src/components/sidebar.ts',
    skeleton: 'src/components/skeleton.ts',
    slider: 'src/components/slider.ts',
    spinner: 'src/components/spinner.ts',
    switch: 'src/components/switch.ts',
    tab: 'src/components/tab.ts',
    table: 'src/components/table.ts',
    tabs: 'src/components/tabs.ts',
    textarea: 'src/components/textarea.ts',
    toast: 'src/components/toast.ts',
    toaster: 'src/components/toaster.ts',
    'toggle-group': 'src/components/toggle-group.ts',
    toggle: 'src/components/toggle.ts',
    tooltip: 'src/components/tooltip.ts',
    // Internal-only — built so components can import it, but deliberately
    // NOT listed in package.json `exports` (no external consumers today).
    'sketchy-base': 'src/sketchy-base.ts',
  },
  unbundle: true,
  format: ['esm', 'cjs'],
  // tsdown's dts generation (rolldown-plugin-dts) doesn't yet support
  // TypeScript 7 — declarations are emitted separately by `tsc
  // --emitDeclarationOnly` in the build script instead.
  dts: false,
  sourcemap: true,
});
