blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/GyeongHoKim/gyeongho-design-system/discussions
    about: For general questions that aren't bugs or feature requests, please use Discussions.
