import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Semantic colour of a {@link Badge}. */
export type BadgeVariant = 'neutral' | 'primary' | 'success' | 'warning' | 'danger' | 'info';

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  /** Semantic colour role. Defaults to `'neutral'`. */
  variant?: BadgeVariant;
}

const badge = tokens.comp.badge;
const c = cssVars.comp.badge;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

/**
 * A small hand-drawn status/label pill. The sketchy outline and solid fill are
 * generated by `@ghds/sketch-core` (via {@link useSketch}); every colour,
 * padding and sketch parameter comes from `@ghds/tokens` (`comp.badge.*`).
 *
 * Renders a plain `<span>`, so it is presentational by default — pass a `role`
 * (e.g. `role="status"`) or `aria-label` when the badge conveys live state.
 */
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(function Badge(
  { variant = 'neutral', children, style, ...rest },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLSpanElement>({
    fillStyle: 'solid',
    roughness: badge.sketch.roughness,
    bowing: badge.sketch.bowing,
    inset: INSET,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);

  const rootStyle: CSSProperties = {
    // Scopes the `SketchSurface` (`z-index: -1`) to this badge so an opaque
    // ancestor can't paint over it (see `sketchHostStyle`).
    ...sketchHostStyle,
    display: 'inline-flex',
    alignItems: 'center',
    gap: badge.gap,
    boxSizing: 'border-box',
    padding: `${badge.padding.vertical} ${badge.padding.horizontal}`,
    color: c.text[variant],
    fontFamily: tokens.sys.typography.caption.fontFamily,
    fontSize: tokens.sys.typography.caption.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.caption.lineHeight),
    whiteSpace: 'nowrap',
    ...style,
  };

  return (
    <span ref={ref} style={rootStyle} {...rest}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke[variant]}
        strokeWidth={STROKE_WIDTH}
        fillColor={c.bg[variant]}
        fillRendering="fill"
      />
      <span style={{ position: 'relative' }}>{children}</span>
    </span>
  );
});
