import { line, rectangle, type SketchDrawable } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { type CSSProperties, useMemo } from 'react';
import { cssVars } from '../lib/cssVars.js';
import { toPx } from '../lib/units.js';

/** Kind of chart to render. */
export type ChartType = 'bar' | 'line';

/** One data series. */
export interface ChartSeries {
  name: string;
  data: number[];
}

export interface ChartProps {
  /** `'bar'` or `'line'`. */
  type: ChartType;
  /** The series to plot (shares the same category axis). */
  series: ChartSeries[];
  /** X-axis category labels (one per data point). */
  categories?: string[];
  /** SVG width in px. Defaults to `480`. */
  width?: number;
  /** SVG height in px. Defaults to `280`. */
  height?: number;
  /** Show the series legend. Defaults to `true`. */
  legend?: boolean;
  /** Accessible label describing the chart. */
  'aria-label'?: string;
}

const chart = tokens.comp.chart;
const c = cssVars.comp.chart;
const STROKE_WIDTH = toPx(chart.stroke.width);
/** Fixed base seed so geometry is deterministic across renders/SSR/snapshots. */
const SEED_BASE = 1337;
const SERIES_KEYS = ['1', '2', '3', '4', '5'] as const;

function seriesColor(index: number): string {
  const key = SERIES_KEYS[index % SERIES_KEYS.length] as (typeof SERIES_KEYS)[number];
  return c.series[key];
}

interface PathBundle {
  readonly drawable: SketchDrawable;
  readonly stroke: string;
  readonly fill?: string;
  readonly key: string;
}

/**
 * A minimal hand-drawn chart (v1: `bar` and `line`). Renders one inline,
 * decorative `<svg>` whose geometry is generated by `@ghds/sketch-core`
 * (sketchy bars / line segments) using a fixed seed, so it is deterministic.
 * Series colours come from `@ghds/tokens` (`comp.chart.series.*`), axes/grid
 * from `comp.chart.*`. The chart carries an `aria-label`; a data table should
 * accompany it for full accessibility.
 */
export function Chart({
  type,
  series,
  categories,
  width = 480,
  height = 280,
  legend = true,
  'aria-label': ariaLabel,
}: ChartProps) {
  const padding = { top: 16, right: 16, bottom: 32, left: 40 };
  const plotW = Math.max(1, width - padding.left - padding.right);
  const plotH = Math.max(1, height - padding.top - padding.bottom);

  const pointCount = Math.max(0, ...series.map((s) => s.data.length));
  const maxValue = Math.max(1, ...series.flatMap((s) => s.data));

  const yFor = (value: number) => padding.top + plotH - (value / maxValue) * plotH;
  const baseline = padding.top + plotH;

  // biome-ignore lint/correctness/useExhaustiveDependencies: geometry depends only on the listed inputs; the plot constants and pure scale helpers are derived from them each render
  const { axisPaths, dataPaths } = useMemo(() => {
    let seed = SEED_BASE;
    const nextSeed = () => {
      seed += 1;
      return seed;
    };
    const opts = () => ({
      roughness: chart.sketch.roughness,
      bowing: chart.sketch.bowing,
      seed: nextSeed(),
    });

    // Axes: an L along the left and bottom edges of the plot.
    const axes: PathBundle[] = [
      {
        drawable: line(padding.left, padding.top, padding.left, baseline, opts()),
        stroke: c.axis,
        key: 'axis-y',
      },
      {
        drawable: line(padding.left, baseline, padding.left + plotW, baseline, opts()),
        stroke: c.axis,
        key: 'axis-x',
      },
    ];

    const data: PathBundle[] = [];
    if (pointCount > 0) {
      if (type === 'bar') {
        const groupWidth = plotW / pointCount;
        const barGap = groupWidth * 0.2;
        const barWidth = Math.max(2, (groupWidth - barGap) / series.length);
        series.forEach((s, si) => {
          s.data.forEach((value, pi) => {
            const x = padding.left + pi * groupWidth + barGap / 2 + si * barWidth;
            const y = yFor(value);
            const h = Math.max(1, baseline - y);
            data.push({
              drawable: rectangle(x, y, barWidth, h, { ...opts(), fillStyle: 'solid' }),
              stroke: seriesColor(si),
              fill: seriesColor(si),
              key: `bar-${si}-${pi}`,
            });
          });
        });
      } else {
        const step = pointCount > 1 ? plotW / (pointCount - 1) : 0;
        const xFor = (pi: number) => padding.left + pi * step;
        series.forEach((s, si) => {
          for (let pi = 0; pi < s.data.length - 1; pi += 1) {
            const a = s.data[pi];
            const b = s.data[pi + 1];
            if (a === undefined || b === undefined) {
              continue;
            }
            data.push({
              drawable: line(xFor(pi), yFor(a), xFor(pi + 1), yFor(b), opts()),
              stroke: seriesColor(si),
              key: `line-${si}-${pi}`,
            });
          }
        });
      }
    }

    return { axisPaths: axes, dataPaths: data };
  }, [type, series, width, height, maxValue, pointCount]);

  const renderBundle = (bundle: PathBundle) => (
    <g key={bundle.key}>
      {bundle.fill !== undefined &&
        bundle.drawable.fillPaths.map((d, i) => (
          <path
            // biome-ignore lint/suspicious/noArrayIndexKey: paths are a fixed, ordered IR list
            key={`f-${i}`}
            d={d}
            fill={bundle.fill}
            fillRule="evenodd"
            stroke="none"
          />
        ))}
      {bundle.drawable.strokePaths.map((d, i) => (
        <path
          // biome-ignore lint/suspicious/noArrayIndexKey: paths are a fixed, ordered IR list
          key={`s-${i}`}
          d={d}
          fill="none"
          stroke={bundle.stroke}
          strokeWidth={STROKE_WIDTH}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      ))}
    </g>
  );

  const labelStyle: CSSProperties = {
    fill: c.text,
    fontFamily: tokens.sys.typography.caption.fontFamily,
    fontSize: tokens.sys.typography.caption.fontSize,
  };

  return (
    <figure
      style={{
        margin: 0,
        display: 'inline-flex',
        flexDirection: 'column',
        gap: tokens.sys.spacing.sm,
      }}
    >
      <svg
        role="img"
        aria-label={ariaLabel}
        width={width}
        height={height}
        viewBox={`0 0 ${width} ${height}`}
      >
        {axisPaths.map(renderBundle)}
        {dataPaths.map(renderBundle)}
        {categories?.map((label, pi) => {
          const step =
            type === 'bar' ? plotW / Math.max(1, pointCount) : plotW / Math.max(1, pointCount - 1);
          const x = type === 'bar' ? padding.left + step * pi + step / 2 : padding.left + step * pi;
          return (
            <text
              // biome-ignore lint/suspicious/noArrayIndexKey: categories are a fixed, ordered list aligned to data points
              key={`cat-${pi}`}
              x={x}
              y={baseline + 20}
              textAnchor="middle"
              style={labelStyle}
            >
              {label}
            </text>
          );
        })}
      </svg>
      {legend && series.length > 0 && (
        <ul
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: tokens.sys.spacing.md,
            margin: 0,
            padding: 0,
            listStyle: 'none',
          }}
        >
          {series.map((s, si) => (
            <li
              key={s.name}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: tokens.sys.spacing.xs,
                color: tokens.sys.color.text.secondary,
                fontSize: tokens.sys.typography.caption.fontSize,
                fontFamily: tokens.sys.typography.caption.fontFamily,
              }}
            >
              <span
                aria-hidden="true"
                style={{
                  width: '0.75rem',
                  height: '0.75rem',
                  borderRadius: tokens.sys.radius.sm,
                  background: seriesColor(si),
                }}
              />
              {s.name}
            </li>
          ))}
        </ul>
      )}
    </figure>
  );
}
