import { tokens } from '@ghds/tokens';
import { Label } from '@radix-ui/react-label';
import {
  type ChangeEvent,
  type CSSProperties,
  type FocusEvent,
  forwardRef,
  type TextareaHTMLAttributes,
  useId,
  useLayoutEffect,
  useRef,
  useState,
} from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface TextareaProps extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'size'> {
  /** Visible label. Associated to the textarea via Radix `Label` for accessibility. */
  label?: string;
  /** Error message. When set, the field is marked invalid and the text announced. */
  error?: string;
  /**
   * Grows the field to fit its content instead of scrolling. Measures
   * `scrollHeight` in JS rather than CSS `field-sizing: content`, which is not
   * yet supported in every browser.
   */
  autoResize?: boolean;
}

const textarea = tokens.comp.textarea;
const c = cssVars.comp.textarea;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

function resolveStroke(focused: boolean, hasError: boolean): string {
  if (hasError) {
    return c.stroke.danger;
  }
  return focused ? c.stroke.focus : c.stroke.default;
}

function syncHeight(el: HTMLTextAreaElement): void {
  el.style.height = 'auto';
  el.style.height = `${el.scrollHeight}px`;
}

/**
 * A hand-drawn, multi-line text field. The sketchy box (outline + paper fill)
 * is generated by `@ghds/sketch-core` (via {@link useSketch}); every color,
 * padding, radius, typography and sketch parameter comes from `@ghds/tokens`
 * (`comp.textarea.*`). A Radix `Label` is associated with the native
 * `<textarea>`, and error state is exposed via `aria-invalid` +
 * `aria-describedby` and a `role="alert"` message. The native resize handle is
 * disabled — it visually collides with the hand-drawn border. Set
 * `autoResize` to grow the field to fit its content instead of scrolling.
 */
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea(
  {
    label,
    error,
    autoResize = false,
    id,
    disabled = false,
    style,
    value,
    onFocus,
    onBlur,
    onChange,
    ...rest
  },
  forwardedRef,
) {
  const reactId = useId();
  const inputId = id ?? reactId;
  const errorId = `${inputId}-error`;
  const hasError = error !== undefined && error !== '';

  const [focused, setFocused] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: textarea.sketch.roughness,
    bowing: textarea.sketch.bowing,
    inset: INSET,
  });

  // Syncs on mount (so an uncontrolled `defaultValue` is measured immediately,
  // not just after the first keystroke), whenever `autoResize` toggles (resetting
  // the JS-set height when it turns off), and on programmatic/controlled value
  // changes, which never fire `onChange`. Uncontrolled typing is synced directly
  // from `handleChange` instead, since an uncontrolled `value` never changes here.
  // biome-ignore lint/correctness/useExhaustiveDependencies: `value` isn't read in the body, but must re-run this effect on every controlled value change — the whole point of the dependency.
  useLayoutEffect(() => {
    if (!textareaRef.current) {
      return;
    }
    if (autoResize) {
      syncHeight(textareaRef.current);
    } else {
      textareaRef.current.style.height = '';
    }
  }, [autoResize, value]);

  const handleChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    if (autoResize && value === undefined) {
      syncHeight(event.target);
    }
    onChange?.(event);
  };

  const fieldStyle: CSSProperties = {
    display: 'inline-flex',
    flexDirection: 'column',
    gap: textarea.gap,
    fontFamily: tokens.sys.typography.body.fontFamily,
    ...style,
  };

  const labelStyle: CSSProperties = {
    color: c.text.label,
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.label.lineHeight),
  };

  const controlStyle: CSSProperties = {
    // Scopes the `SketchSurface` (`z-index: -1`) to this control so an opaque
    // ancestor can't paint over it (see `sketchHostStyle`).
    ...sketchHostStyle,
    display: 'flex',
    boxSizing: 'border-box',
  };

  const textareaStyle: CSSProperties = {
    flex: 1,
    boxSizing: 'border-box',
    width: '100%',
    margin: 0,
    padding: `${textarea.padding.vertical} ${textarea.padding.horizontal}`,
    border: 'none',
    outline: 'none',
    background: 'transparent',
    resize: 'none',
    color: disabled ? c.text.disabled : c.text.value,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    fontWeight: tokens.sys.typography.body.fontWeight,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
    cursor: disabled ? 'not-allowed' : 'text',
  };

  const errorStyle: CSSProperties = {
    color: c.stroke.danger,
    fontFamily: tokens.sys.typography.caption.fontFamily,
    fontSize: tokens.sys.typography.caption.fontSize,
    fontWeight: tokens.sys.typography.caption.fontWeight,
    lineHeight: String(tokens.sys.typography.caption.lineHeight),
  };

  const ref = mergeRefs(textareaRef, forwardedRef);

  return (
    <div style={fieldStyle}>
      {label !== undefined && (
        <Label htmlFor={inputId} style={labelStyle}>
          {label}
        </Label>
      )}
      <div ref={sketchRef} style={controlStyle}>
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={resolveStroke(focused, hasError)}
          strokeWidth={STROKE_WIDTH}
          fillColor={disabled ? c.bg.disabled : c.bg.default}
          fillRendering="fill"
        />
        <textarea
          ref={ref}
          id={inputId}
          value={value}
          disabled={disabled}
          aria-invalid={hasError || undefined}
          aria-describedby={hasError ? errorId : undefined}
          style={textareaStyle}
          onChange={handleChange}
          onFocus={(event: FocusEvent<HTMLTextAreaElement>) => {
            setFocused(true);
            onFocus?.(event);
          }}
          onBlur={(event: FocusEvent<HTMLTextAreaElement>) => {
            setFocused(false);
            onBlur?.(event);
          }}
          {...rest}
        />
      </div>
      {hasError && (
        <span id={errorId} role="alert" style={errorStyle}>
          {error}
        </span>
      )}
    </div>
  );
});
