/**
 * @ghds/tokens — Style Dictionary v4 multi-platform build.
 *
 * Source: W3C DTCG tokens in `src/{ref,sys,comp}`. References are resolved by
 * Style Dictionary; this script then emits four platform shapes into `dist/`:
 *
 *   - css   → `dist/css/variables.css`  (:root light + [data-theme="dark"] + prefers-color-scheme)
 *   - ts    → `dist/ts/{light,dark}.{js,d.ts}` + `dist/index.{js,d.ts}` (web, value strings)
 *   - rn    → `dist/rn/{light,dark}.{js,d.ts}` + `dist/rn/index.{js,d.ts}` (px/ms → numbers)
 *   - json  → `dist/json/tokens.json` + `dist/json/tokens.dark.json` (platform-agnostic, resolved)
 *
 * Every output PRESERVES the semantic token path: CSS uses `--{path-with-dashes}`,
 * the JS/JSON/RN objects keep the original nested keys (`tokens.sys.color.bg.primary.default`).
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import StyleDictionary from 'style-dictionary';

const HEADER =
  '/**\n * GHDS design tokens — GENERATED by @ghds/tokens build. Do not edit by hand.\n */\n';
const THEMES = ['light', 'dark'];

/** Build a nested plain object of resolved values keyed by each token's semantic path. */
function buildNested(allTokens) {
  const root = {};
  for (const token of allTokens) {
    const segs = token.path;
    let node = root;
    for (let i = 0; i < segs.length; i++) {
      const seg = segs[i];
      if (i === segs.length - 1) {
        node[seg] = token.$value;
      } else {
        node[seg] ??= {};
        node = node[seg];
      }
    }
  }
  return root;
}

/** Render a nested value object as a precise TypeScript literal type. */
function toDts(value, indent = '  ') {
  if (value === null || typeof value !== 'object') {
    return typeof value === 'number' ? String(value) : JSON.stringify(value);
  }
  const next = `${indent}  `;
  const entries = Object.entries(value).map(
    ([key, child]) => `${next}readonly ${JSON.stringify(key)}: ${toDts(child, next)};`,
  );
  return `{\n${entries.join('\n')}\n${indent}}`;
}

StyleDictionary.registerTransform({
  name: 'ghds/value/rn',
  type: 'value',
  transitive: true,
  filter: (token) => typeof token.$value === 'string',
  transform: (token) => {
    const px = /^(-?\d*\.?\d+)px$/.exec(token.$value);
    if (px) return Number(px[1]);
    const ms = /^(-?\d*\.?\d+)ms$/.exec(token.$value);
    if (ms) return Number(ms[1]);
    return token.$value;
  },
});

StyleDictionary.registerFormat({
  name: 'ghds/css',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root';
    const lines = dictionary.allTokens.map(
      (token) => `  --${token.path.join('-')}: ${token.$value};`,
    );
    return `${HEADER}${selector} {\n${lines.join('\n')}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'ghds/esm',
  format: ({ dictionary, options }) =>
    `${HEADER}export const ${options.varName} = ${JSON.stringify(buildNested(dictionary.allTokens), null, 2)};\n`,
});

StyleDictionary.registerFormat({
  name: 'ghds/dts',
  format: ({ dictionary, options }) =>
    `${HEADER}export declare const ${options.varName}: ${toDts(buildNested(dictionary.allTokens))};\n`,
});

StyleDictionary.registerFormat({
  name: 'ghds/json',
  format: ({ dictionary }) => `${JSON.stringify(buildNested(dictionary.allTokens), null, 2)}\n`,
});

function makeStyleDictionary(theme) {
  return new StyleDictionary({
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: [
      'src/ref/**/*.json',
      'src/sys/_shared.json',
      `src/sys/${theme}.json`,
      'src/comp/**/*.json',
    ],
    platforms: {
      css: {
        transforms: [],
        buildPath: 'dist/css/',
        files: [
          {
            destination: `_${theme}.css`,
            format: 'ghds/css',
            options: { selector: theme === 'light' ? ':root' : '[data-theme="dark"]' },
          },
        ],
      },
      ts: {
        transforms: [],
        buildPath: 'dist/ts/',
        files: [
          {
            destination: `${theme}.js`,
            format: 'ghds/esm',
            options: { varName: `${theme}Tokens` },
          },
          {
            destination: `${theme}.d.ts`,
            format: 'ghds/dts',
            options: { varName: `${theme}Tokens` },
          },
        ],
      },
      rn: {
        transforms: ['ghds/value/rn'],
        buildPath: 'dist/rn/',
        files: [
          {
            destination: `${theme}.js`,
            format: 'ghds/esm',
            options: { varName: `${theme}Tokens` },
          },
          {
            destination: `${theme}.d.ts`,
            format: 'ghds/dts',
            options: { varName: `${theme}Tokens` },
          },
        ],
      },
      json: {
        transforms: [],
        buildPath: 'dist/json/',
        files: [
          {
            destination: theme === 'light' ? 'tokens.json' : 'tokens.dark.json',
            format: 'ghds/json',
          },
        ],
      },
    },
  });
}

/** Inner `--var: value;` lines of a generated single-selector CSS block. */
function cssBody(css) {
  return css.slice(css.indexOf('{') + 1, css.lastIndexOf('}')).replace(/^\n+|\n+$/g, '');
}

async function main() {
  const dist = path.resolve('dist');
  await fs.rm(dist, { recursive: true, force: true });

  for (const theme of THEMES) {
    await makeStyleDictionary(theme).buildAllPlatforms();
  }

  // Combined CSS: light :root, dark attribute selector, dark prefers-color-scheme.
  const lightCss = await fs.readFile('dist/css/_light.css', 'utf8');
  const darkCss = await fs.readFile('dist/css/_dark.css', 'utf8');
  const darkBody = cssBody(darkCss);
  const mediaBody = darkBody
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');
  const combined = [
    HEADER,
    `:root {\n${cssBody(lightCss)}\n}`,
    '',
    `[data-theme="dark"] {\n${darkBody}\n}`,
    '',
    `@media (prefers-color-scheme: dark) {\n  :root {\n${mediaBody}\n  }\n}`,
    '',
  ].join('\n');
  await fs.writeFile('dist/css/variables.css', combined);
  await fs.rm('dist/css/_light.css');
  await fs.rm('dist/css/_dark.css');

  // Barrel entries.
  const webIndex = `${HEADER}export { lightTokens, lightTokens as tokens } from './ts/light.js';\nexport { darkTokens } from './ts/dark.js';\n`;
  await fs.writeFile('dist/index.js', webIndex);
  await fs.writeFile('dist/index.d.ts', webIndex);

  const rnIndex = `${HEADER}export { lightTokens } from './light.js';\nexport { darkTokens } from './dark.js';\n`;
  await fs.writeFile('dist/rn/index.js', rnIndex);
  await fs.writeFile('dist/rn/index.d.ts', rnIndex);

  console.log('@ghds/tokens: built css, ts, rn, json for', THEMES.join(' + '));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
