/**
 * @ghds/tokens — Style Dictionary v4 multi-platform build.
 *
 * Source: W3C DTCG tokens in `src/{ref,sys,comp}`. References are resolved by
 * Style Dictionary; this script then emits four platform shapes into `dist/`:
 *
 *   - css   → `dist/css/variables.css`  (:root light + [data-theme="dark"] + prefers-color-scheme)
 *   - ts    → `dist/ts/{light,dark}.{js,d.ts}` + `dist/index.{js,d.ts}` (web, value strings)
 *   - rn    → `dist/rn/{light,dark}.{js,d.ts}` + `dist/rn/index.{js,d.ts}` (px/ms → numbers)
 *   - json  → `dist/json/tokens.json` + `dist/json/tokens.dark.json` (platform-agnostic, resolved)
 *
 * Every output PRESERVES the semantic token path: CSS uses `--{path-with-dashes}`,
 * the JS/JSON/RN objects keep the original nested keys (`tokens.sys.color.bg.primary.default`).
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import StyleDictionary from 'style-dictionary';

const HEADER =
  '/**\n * GHDS design tokens — GENERATED by @ghds/tokens build. Do not edit by hand.\n */\n';
const THEMES = ['light', 'dark'];

/** Build a nested plain object of resolved values keyed by each token's semantic path. */
function buildNested(allTokens) {
  const root = {};
  for (const token of allTokens) {
    const segs = token.path;
    let node = root;
    for (let i = 0; i < segs.length; i++) {
      const seg = segs[i];
      if (i === segs.length - 1) {
        node[seg] = token.$value;
      } else {
        node[seg] ??= {};
        node = node[seg];
      }
    }
  }
  return root;
}

/** Render a nested value object as a precise TypeScript literal type. */
function toDts(value, indent = '  ') {
  if (value === null || typeof value !== 'object') {
    return typeof value === 'number' ? String(value) : JSON.stringify(value);
  }
  const next = `${indent}  `;
  const entries = Object.entries(value).map(
    ([key, child]) => `${next}readonly ${JSON.stringify(key)}: ${toDts(child, next)};`,
  );
  return `{\n${entries.join('\n')}\n${indent}}`;
}

/** Strip a length/duration unit (`16px` → 16, `200ms` → 200); pass through otherwise. */
function rnNumber(value) {
  const px = /^(-?\d*\.?\d+)px$/.exec(value);
  if (px) return Number(px[1]);
  const ms = /^(-?\d*\.?\d+)ms$/.exec(value);
  if (ms) return Number(ms[1]);
  return value;
}

/**
 * Convert a CSS `box-shadow` string into a React Native shadow object that RN can
 * actually consume (`shadowColor`/`shadowOffset`/`shadowOpacity`/`shadowRadius` for iOS,
 * `elevation` for Android). Input shape: `<x> <y> <blur> <spread> rgba(r, g, b, a)`.
 */
function rnShadow(value) {
  const rgba = /rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)/.exec(value);
  const lengths = value
    .replace(/rgba?\([^)]*\)/, '')
    .trim()
    .split(/\s+/)
    .map((part) => rnNumber(part));
  const [x = 0, y = 0, blur = 0] = lengths;
  const toHex = (n) => Number(n).toString(16).padStart(2, '0');
  const shadowColor = rgba ? `#${toHex(rgba[1])}${toHex(rgba[2])}${toHex(rgba[3])}` : '#000000';
  const shadowOpacity = rgba?.[4] !== undefined ? Number(rgba[4]) : 1;
  return {
    shadowColor,
    shadowOffset: { width: x, height: y },
    shadowOpacity,
    shadowRadius: blur,
    elevation: Math.round(blur),
  };
}

/**
 * React Native does not support CSS comma-separated font stacks — `fontFamily`
 * accepts a single family name. This map picks the RN-appropriate face from
 * each GHDS web stack. The chosen face must include both Latin and Korean
 * glyphs (RN cannot do per-glyph fallback across families), so the Korean
 * face is preferred for body/UI and display.
 *
 *   sketch → Gaegu  (hand-drawn Korean, also covers Latin)
 *   sans   → Pretendard (Korean sans, also covers Latin)
 *   mono   → Menlo  (iOS/Android system mono; Korean falls back to OS)
 *
 * If a stack is not in this map, the first quoted family name is extracted.
 */
const RN_FONT_FAMILY_MAP = {
  "'Gochi Hand', 'Gaegu', 'Comic Sans MS', cursive": 'Gaegu',
  "'Nunito Sans Variable', 'Pretendard', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans KR', sans-serif":
    'Pretendard',
  "ui-monospace, 'SFMono-Regular', 'Menlo', 'Noto Sans KR', monospace": 'Menlo',
};

/** Extract a single RN-compatible font family name from a CSS font stack. */
function rnFontFamily(value) {
  const mapped = RN_FONT_FAMILY_MAP[value];
  if (mapped) return mapped;
  // Fallback: first quoted name, or first token before a comma.
  const quoted = /'([^']+)'/.exec(value);
  if (quoted) return quoted[1];
  return value.split(',')[0].trim();
}

StyleDictionary.registerTransform({
  name: 'ghds/value/rn',
  type: 'value',
  transitive: true,
  filter: (token) => typeof token.$value === 'string',
  transform: (token) => {
    if (token.$type === 'shadow') return rnShadow(token.$value);
    if (token.$type === 'fontFamily') return rnFontFamily(token.$value);
    return rnNumber(token.$value);
  },
});

StyleDictionary.registerFormat({
  name: 'ghds/css',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root';
    const lines = dictionary.allTokens.map(
      (token) => `  --${token.path.join('-')}: ${token.$value};`,
    );
    return `${HEADER}${selector} {\n${lines.join('\n')}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'ghds/esm',
  format: ({ dictionary, options }) =>
    `${HEADER}export const ${options.varName} = ${JSON.stringify(buildNested(dictionary.allTokens), null, 2)};\n`,
});

StyleDictionary.registerFormat({
  name: 'ghds/dts',
  format: ({ dictionary, options }) =>
    `${HEADER}export declare const ${options.varName}: ${toDts(buildNested(dictionary.allTokens))};\n`,
});

StyleDictionary.registerFormat({
  name: 'ghds/json',
  format: ({ dictionary }) => `${JSON.stringify(buildNested(dictionary.allTokens), null, 2)}\n`,
});

function makeStyleDictionary(theme) {
  return new StyleDictionary({
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: [
      'src/ref/**/*.json',
      'src/sys/_shared.json',
      `src/sys/${theme}.json`,
      'src/comp/**/*.json',
    ],
    platforms: {
      css: {
        transforms: [],
        buildPath: 'dist/css/',
        files: [
          {
            destination: `_${theme}.css`,
            format: 'ghds/css',
            options: { selector: theme === 'light' ? ':root' : '[data-theme="dark"]' },
          },
        ],
      },
      ts: {
        transforms: [],
        buildPath: 'dist/ts/',
        files: [
          {
            destination: `${theme}.js`,
            format: 'ghds/esm',
            options: { varName: `${theme}Tokens` },
          },
          {
            destination: `${theme}.d.ts`,
            format: 'ghds/dts',
            options: { varName: `${theme}Tokens` },
          },
        ],
      },
      rn: {
        transforms: ['ghds/value/rn'],
        buildPath: 'dist/rn/',
        files: [
          {
            destination: `${theme}.js`,
            format: 'ghds/esm',
            options: { varName: `${theme}Tokens` },
          },
          {
            destination: `${theme}.d.ts`,
            format: 'ghds/dts',
            options: { varName: `${theme}Tokens` },
          },
        ],
      },
      json: {
        transforms: [],
        buildPath: 'dist/json/',
        files: [
          {
            destination: theme === 'light' ? 'tokens.json' : 'tokens.dark.json',
            format: 'ghds/json',
          },
        ],
      },
    },
  });
}

/** Inner `--var: value;` lines of a generated single-selector CSS block. */
function cssBody(css) {
  return css.slice(css.indexOf('{') + 1, css.lastIndexOf('}')).replace(/^\n+|\n+$/g, '');
}

async function main() {
  const dist = path.resolve('dist');
  await fs.rm(dist, { recursive: true, force: true });

  for (const theme of THEMES) {
    await makeStyleDictionary(theme).buildAllPlatforms();
  }

  // Combined CSS: light :root, dark attribute selector, dark prefers-color-scheme.
  const lightCss = await fs.readFile('dist/css/_light.css', 'utf8');
  const darkCss = await fs.readFile('dist/css/_dark.css', 'utf8');
  const darkBody = cssBody(darkCss);
  const mediaBody = darkBody
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');
  // `:root` is the light default. `[data-theme="dark"]` (higher specificity) always wins.
  // The OS-preference fallback is scoped to `:root:not([data-theme])` so an explicit
  // `data-theme="light"` is NOT overridden by a dark OS setting.
  const combined = [
    HEADER,
    `:root {\n${cssBody(lightCss)}\n}`,
    '',
    `[data-theme="dark"] {\n${darkBody}\n}`,
    '',
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n${mediaBody}\n  }\n}`,
    '',
  ].join('\n');
  await fs.writeFile('dist/css/variables.css', combined);
  await fs.rm('dist/css/_light.css');
  await fs.rm('dist/css/_dark.css');

  // Barrel entries.
  const webIndex = `${HEADER}export { lightTokens, lightTokens as tokens } from './ts/light.js';\nexport { darkTokens } from './ts/dark.js';\n`;
  await fs.writeFile('dist/index.js', webIndex);
  await fs.writeFile('dist/index.d.ts', webIndex);

  const rnIndex = `${HEADER}export { lightTokens } from './light.js';\nexport { darkTokens } from './dark.js';\n`;
  await fs.writeFile('dist/rn/index.js', rnIndex);
  await fs.writeFile('dist/rn/index.d.ts', rnIndex);

  console.log('@ghds/tokens: built css, ts, rn, json for', THEMES.join(' + '));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
