import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    // Public components — one subpath per entry, kebab-case.
    accordion: 'src/components/Accordion.tsx',
    alert: 'src/components/Alert.tsx',
    'alert-dialog': 'src/components/AlertDialog.tsx',
    'aspect-ratio': 'src/components/AspectRatio.tsx',
    avatar: 'src/components/Avatar.tsx',
    badge: 'src/components/Badge.tsx',
    breadcrumb: 'src/components/Breadcrumb.tsx',
    button: 'src/components/Button.tsx',
    'button-group': 'src/components/ButtonGroup.tsx',
    calendar: 'src/components/Calendar.tsx',
    card: 'src/components/Card.tsx',
    chart: 'src/components/Chart.tsx',
    checkbox: 'src/components/Checkbox.tsx',
    'checkbox-group': 'src/components/CheckboxGroup.tsx',
    collapsible: 'src/components/Collapsible.tsx',
    combobox: 'src/components/Combobox.tsx',
    command: 'src/components/Command.tsx',
    'context-menu': 'src/components/ContextMenu.tsx',
    'date-picker': 'src/components/DatePicker.tsx',
    direction: 'src/components/Direction.tsx',
    drawer: 'src/components/Drawer.tsx',
    empty: 'src/components/Empty.tsx',
    'form-field': 'src/components/FormField.tsx',
    'hover-card': 'src/components/HoverCard.tsx',
    icon: 'src/components/Icon.tsx',
    input: 'src/components/Input.tsx',
    'input-group': 'src/components/InputGroup.tsx',
    'input-otp': 'src/components/InputOTP.tsx',
    item: 'src/components/Item.tsx',
    kbd: 'src/components/Kbd.tsx',
    label: 'src/components/Label.tsx',
    menu: 'src/components/Menu.tsx',
    menubar: 'src/components/Menubar.tsx',
    modal: 'src/components/Modal.tsx',
    'native-select': 'src/components/NativeSelect.tsx',
    'navigation-menu': 'src/components/NavigationMenu.tsx',
    pagination: 'src/components/Pagination.tsx',
    popover: 'src/components/Popover.tsx',
    progress: 'src/components/Progress.tsx',
    radio: 'src/components/Radio.tsx',
    'radio-group': 'src/components/RadioGroup.tsx',
    'scroll-area': 'src/components/ScrollArea.tsx',
    select: 'src/components/Select.tsx',
    separator: 'src/components/Separator.tsx',
    sheet: 'src/components/Sheet.tsx',
    sidebar: 'src/components/Sidebar.tsx',
    skeleton: 'src/components/Skeleton.tsx',
    slider: 'src/components/Slider.tsx',
    spinner: 'src/components/Spinner.tsx',
    switch: 'src/components/Switch.tsx',
    table: 'src/components/Table.tsx',
    tabs: 'src/components/Tabs.tsx',
    textarea: 'src/components/Textarea.tsx',
    toast: 'src/components/Toast.tsx',
    toggle: 'src/components/Toggle.tsx',
    'toggle-group': 'src/components/ToggleGroup.tsx',
    tooltip: 'src/components/Tooltip.tsx',
    // Internal-only — built so components can import them, but deliberately
    // NOT listed in package.json `exports` (no external consumers today).
    'sketch-surface': 'src/components/SketchSurface.tsx',
    'use-sketch': 'src/hooks/useSketch.ts',
    'merge-refs': 'src/lib/mergeRefs.ts',
    units: 'src/lib/units.ts',
  },
  unbundle: true,
  format: ['esm', 'cjs'],
  // tsdown's dts generation (rolldown-plugin-dts) doesn't yet support
  // TypeScript 7 — declarations are emitted separately by `tsc
  // --emitDeclarationOnly` in the build script instead.
  dts: false,
  sourcemap: true,
});
